all:
  children:
    kafka_servers:
      hosts:
        kafka-broker-1:
          ansible_host: 192.168.56.3
          kafka_role: broker
      vars:
        ansible_user: user
        ansible_password: "user"
        # Security Note: Use ansible-vault for passwords or SSH keys for authentication
        ansible_become: true
        ansible_become_method: sudo
