all:
  children:
    flink_servers:
      hosts:
        flink-master:
          ansible_host: 192.168.178.46
          flink_role: master
        flink-worker-1:
          ansible_host: 192.168.178.46
          flink_role: worker
      vars:
        ansible_user: user
        ansible_password: "user"
        # Security Note: Use ansible-vault for passwords or SSH keys for authentication
        ansible_become: true
        ansible_become_method: sudo
        ansible_become_password: "user"
