---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: restart flink
  systemd:
    name: flink
    state: restarted
  when: not ansible_check_mode and (flink_start_service | default(true))
