all:
  children:
    sonarqube_servers:
      hosts:
        sonarqube-server:
          ansible_host: 10.0.2.15
      vars:
        ansible_user: user
        ansible_password: user
        ansible_become: true
        ansible_become_method: sudo
        ansible_become_password: user
