all:
  children:
    sonarqube_servers:
      hosts:
        sonarqube-server:
          ansible_host: 192.168.178.43
      vars:
        ansible_user: user
        ansible_password: user
        ansible_become: true
        ansible_become_method: sudo
        ansible_become_password: user
